# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/atharva/ece540_supreet/ece540_final_project/RVfpga/rvfpga_src/rvfpganexys.xdc

# XDC: /home/atharva/ece540_supreet/ece540_final_project/RVfpga/rvfpga_src/LiteDRAM/liteDRAM.xdc

# IP: ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet
